version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE= estudos
      - MYSQL_USER= root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  
  rebbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672